Repository Arch2x/codeit, pull requests merged in 2021-01, with the labels that each got.

#9 Place new template
  codeit/codeit.py
Labels: Status: Approved, enhancement

#18 Add TXT file
  requirements.txt
Labels: Status: Approved, enhancement, repo

#19 Add spaces in README
  README.md
Labels: markdown

#22 3rd function
  codeit/codeit.py
  codeit/codeitHelp.py
  codeit/codeitInit.py
Labels: JWoC, Level: Easy, Status: Approved, repo

#23 Updated the colour scheme and args pattern.
  codeit/codeitHelp.py
Labels: Status: Approved, good first issue, repo
